spring.application.name=smart-lead-qualification

ai.model=meta-llama/Llama-3.3-70B-Instruct
ai.token=${HF_TOKEN:placeholder}

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.sqs.endpoint=http://localhost:4566
aws.queque-url=http://localhost:4566/000000000000/

springdoc.swagger-ui.path=/api/docs
springdoc.swagger-ui.disable-swagger-default-url=true
