spring.application.name=smart-lead-qualification

# HuggingFace - OpenAI
spring.ai.openai.api-key=${HF_TOKEN:placeholder}
spring.ai.openai.chat.model=meta-llama/Llama-3.3-70B-Instruct

spring.ai.openai.base-url=https://router.huggingface.co/v1

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/smartlead
spring.datasource.username=myuser
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.driver-class-name=org.postgresql.Driver

# AWS SQS
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.sqs.endpoint=http://localhost:4566
aws.queque-url=http://localhost:4566/000000000000/message-analysis-queue
app.queue.name=message-analysis-queue

# OpenAPI
springdoc.swagger-ui.path=/api/docs
springdoc.swagger-ui.disable-swagger-default-url=true

# AI stub
enable.fake.hf=false

# Management endpoints
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always

# Enable liveness and readiness probes
management.endpoint.health.probes.enabled=true
management.health.mongodb.enabled=false

# Enable liveness & readiness states
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

# Observability
# For development keep 1.0 for all traces to export, production environment keep 0.1
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs