CREATE TABLE leads
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    type          VARCHAR(255),
    urgency_level VARCHAR(255),
    description   VARCHAR(255),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT pk_leads PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    CLOB,
    status     VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);