CREATE TABLE leads
(
    lead_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    type          VARCHAR(255),
    urgency_level VARCHAR(255),
    description   VARCHAR(255),
    message_id    BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_leads PRIMARY KEY (lead_id)
);

CREATE TABLE messages
(
    message_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content      OID,
    status       VARCHAR(255),
    lead_lead_id BIGINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (message_id)
);

ALTER TABLE leads
    ADD CONSTRAINT uc_leads_message UNIQUE (message_id);

ALTER TABLE leads
    ADD CONSTRAINT FK_LEADS_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (message_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_LEAD_LEAD FOREIGN KEY (lead_lead_id) REFERENCES leads (lead_id);